
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.network "public_network", bridge: "Default Switch"

    config.vm.provider "hyperv" do |provider|  
        provider.cpus = 4
        provider.maxmemory = 6000
    end

    config.vm.provision "shell", path: "setup.sh", privileged: false, env: {"BASE_DIR" => "/home/vagrant"}

end