
def init_database(b):
    b.dmtype("/database")
    b.dmproc("Close")
    b.dmproc("Error")
    b.dmproc("ErrorMsg")
    b.dmproc("New")
    b.dmproc("Open")

    b.dmtype("/database/query")
    b.dmproc("Add")
    b.dmproc("Clear")
    b.dmproc("Close")
    b.dmproc("Columns")
    b.dmproc("Error")
    b.dmproc("ErrorMsg")
    b.dmproc("Execute")
    b.dmproc("GetColumn")
    b.dmproc("GetRowData")
    b.dmproc("New")
    b.dmproc("NextRow")
    b.dmproc("Reset")
    b.dmproc("RowsAffected")