
from .common import Common

def init_client(b):
    b.dmtype("/client")
    b.parent_type("/datum")

    Common.mouse_procs(b)
        
    b.dmproc("AllowUpload")
    b.dmproc("Center")
    b.dmproc("CheckPassport")
    b.dmproc("Command")
    b.dmproc("Export")
    b.dmproc("GetAPI")
    b.dmproc("Import")
    b.dmproc("IsByondMember")
    b.dmproc("MeasureText")
    b.dmproc("SendPage")
    b.dmproc("SetAPI")
    b.dmproc("SoundQuery")

    b.dmproc("Move")
    b.dmproc("Stat")

    b.dmproc("North")
    b.dmproc("Northeast")
    b.dmproc("Northwest")
    b.dmproc("South")
    b.dmproc("Southeast")
    b.dmproc("Southwest")
    b.dmproc("West")
    b.dmproc("East")

    b.dmvar("address")
    b.dmvar("authenticate")
    b.dmvar("bounds")
    b.dmvar("byond_build")
    b.dmvar("byond_version")
    b.dmvar("CGI")
    b.dmvar("ckey")
    b.dmvar("color")
    b.dmvar("command_text")
    b.dmvar("connection")
    b.dmvar("control_freak")
    b.dmvar("computer_id")
    b.dmvar("default_verb_category")
    b.dmvar("dir")
    b.dmvar("edge_limit")
    b.dmvar("eye")
    b.dmvar("fps")
    b.dmvar("gender")
    b.dmvar("glide_size")
    b.dmvar("images")
    b.dmvar("inactivity")
    b.dmvar("key")
    b.dmvar("lazy_eye")
    b.dmvar("mob")
    b.dmvar("mouse_pointer_icon")
    b.dmvar("perspective")
    b.dmvar("pixel_x")
    b.dmvar("pixel_y")
    b.dmvar("pixel_w")
    b.dmvar("pixel_z")
    b.dmvar("pixel_z")
    b.dmvar("preload_rsc")
    b.dmvar("screen")
    b.dmvar("script")
    b.dmvar("show_map")
    b.dmvar("show_popup_menus")
    b.dmvar("show_verb_panel")
    b.dmvar("statobj")
    b.dmvar("statpanel")
    b.dmvar("tick_lag")
    b.dmvar("timezone")
    b.dmvar("verbs")
    b.dmvar("view")
    b.dmvar("virtual_eye")
