
class Common(object):
    def mouse_procs(b):
        b.dmproc("Click")
        b.dmproc("DblClick")
        b.dmproc("MouseDown")
        b.dmproc("MouseDrag")
        b.dmproc("MouseDrop")
        b.dmproc("MouseEntered")
        b.dmproc("MouseExited")
        b.dmproc("MouseMove")
        b.dmproc("MouseUp")
        b.dmproc("MouseWheel")

    def movement_procs(b):
        b.dmproc("Cross")
        b.dmproc("Crossed")
        b.dmproc("Enter")
        b.dmproc("Entered")
        b.dmproc("Exit")
        b.dmproc("Exited")
        b.dmproc("Uncross")
        b.dmproc("Uncrossed")

    def appearance_vars(b):
        # cloned vars
        b.dmvar("alpha")
        b.dmvar("appearance_flags")
        b.dmvar("blend_mode")
        b.dmvar("color")
        b.dmvar("desc")
        b.dmvar("gender")
        b.dmvar("icon")
        b.dmvar("icon_state")
        b.dmvar("invisibility")
        b.dmvar("infra_luminosity")
        b.dmvar("filters")
        b.dmvar("layer")
        b.dmvar("luminosity")
        b.dmvar("maptext")
        b.dmvar("maptext_width")
        b.dmvar("maptext_height")
        b.dmvar("maptext_x")
        b.dmvar("maptext_y")
        b.dmvar("mouse_over_pointer")
        b.dmvar("mouse_drag_pointer")
        b.dmvar("mouse_drop_pointer")
        b.dmvar("mouse_drop_zone")
        b.dmvar("mouse_opacity")
        b.dmvar("name")
        b.dmvar("opacity")
        b.dmvar("overlays")
        b.dmvar("override")
        b.dmvar("pixel_x")
        b.dmvar("pixel_y")
        b.dmvar("pixel_w")
        b.dmvar("pixel_z")
        b.dmvar("plane")
        b.dmvar("render_source")
        b.dmvar("render_target")
        b.dmvar("suffix")
        b.dmvar("text")
        b.dmvar("transform")
        b.dmvar("underlays")
        b.dmvar("vis_flags")

        # non-cloned vars
        b.dmvar("density")
        b.dmvar("dir")
        b.dmvar("verbs")