
def init_sound(b):
    b.dmtype("/sound")

    b.dmvar("file")
    b.dmvar("repeat")
    b.dmvar("wait")
    b.dmvar("channel")
    b.dmvar("volume")
    b.dmvar("frequency")
    b.dmvar("offset")
    b.dmvar("len")
    b.dmvar("pan")
    b.dmvar("priority")
    b.dmvar("status")
    b.dmvar("x")
    b.dmvar("y")
    b.dmvar("z")
    b.dmvar("falloff")
    b.dmvar("environment")
    b.dmvar("echo")